version: '2'
services:
  build:
    build:
        dockerfile: ./build/Dockerfile
        context: .
    image: microsoft/dotnetbuildimage
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore3 && dotnet publish3 -c release -o ~/bin/release/publishoutput"